services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kiranraj@1234
      POSTGRES_DB: my-app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cent-stage-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - cent-stage-network
    restart: unless-stopped
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - cent-stage-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  cent-stage-network:
    external: true
